# Generated by Django 4.2.11 on 2024-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('Ingredients', models.CharField(max_length=100)),
            ],
        ),
    ]
